// Generated by CoffeeScript 2.4.1
(function() {
  exports.handler = function(event, context, callback) {
    return callback(null, {
      statusCode: 200,
      body: 'Hello, World'
    });
  };

}).call(this);
